from pathlib import Path
from typing import Optional, Sequence, Union

__version__: str

def load_from_file(path: str) -> RetargetingConfig: ...

class RetargetingConfig:
    def __init__(
        self,
        type: str,
        urdf_path: str,
        *,
        add_dummy_free_joint: bool = False,
        target_link_human_indices: Union[Sequence[int], Sequence[Sequence[int]], None] = None,
        wrist_link_name: Optional[str] = None,
        target_link_names: Optional[Sequence[str]] = None,
        target_joint_names: Optional[Sequence[str]] = None,
        target_origin_link_names: Optional[Sequence[str]] = None,
        target_task_link_names: Optional[Sequence[str]] = None,
        finger_tip_link_names: Optional[Sequence[str]] = None,
        scaling_factor: float = 1.0,
        normal_delta: float = 4e-3,
        huber_delta: float = 2e-2,
        project_dist: float = 0.03,
        escape_dist: float = 0.05,
        has_joint_limits: bool = True,
        ignore_mimic_joint: bool = False,
        low_pass_alpha: float = 0.1,
        urdf_dir: Union[str, Path, None] = None,
    ) -> None: ...
    @staticmethod
    def from_file(path: str) -> RetargetingConfig: ...
    def build(self) -> SeqRetargeting: ...
    @property
    def type_(self) -> str: ...
    @property
    def urdf_path(self) -> str: ...
    @property
    def urdf_dir(self) -> str: ...
    @property
    def add_dummy_free_joint(self) -> bool: ...
    @property
    def target_link_human_indices(self) -> Optional[list[int]]: ...
    @property
    def wrist_link_name(self) -> Optional[str]: ...
    @property
    def target_link_names(self) -> Optional[list[str]]: ...
    @property
    def target_joint_names(self) -> Optional[list[str]]: ...
    @property
    def target_origin_link_names(self) -> Optional[list[str]]: ...
    @property
    def target_task_link_names(self) -> Optional[list[str]]: ...
    @property
    def finger_tip_link_names(self) -> Optional[list[str]]: ...
    @property
    def scaling_factor(self) -> float: ...
    @property
    def normal_delta(self) -> float: ...
    @property
    def huber_delta(self) -> float: ...
    @property
    def project_dist(self) -> float: ...
    @property
    def escape_dist(self) -> float: ...
    @property
    def has_joint_limits(self) -> bool: ...
    @property
    def ignore_mimic_joint(self) -> bool: ...
    @property
    def low_pass_alpha(self) -> float: ...

class SeqRetargeting:
    def retarget(
        self, ref_value: Sequence[float], fixed_qpos: Optional[Sequence[float]] = None
    ) -> list[float]: ...
    def reset(self) -> None: ...
    def set_qpos(self, robot_qpos: Sequence[float]) -> None: ...
    def get_qpos(self, fixed_qpos: Optional[Sequence[float]] = None) -> list[float]: ...
    def link_positions(
        self, robot_qpos: Sequence[float], link_names: Sequence[str]
    ) -> list[tuple[float, float, float]]: ...
    @property
    def joint_names(self) -> list[str]: ...
    @property
    def link_names(self) -> list[str]: ...
    @property
    def fixed_dof(self) -> int: ...
    @property
    def target_dof(self) -> int: ...
